### ISSUE TITLE
What to do with it at the moment, did you find any solution?

### ISSUE THREAD

**Issue by sheldygg** [Kappador/twitch-integrity#4]
:(

**Comment by MyNameJeff12123** [comment]
also interested

**Comment by sheldygg** [comment]
I found out that this is a JWT token, which will require an even more secret token to generate

**Comment by Kappador** [comment]
There are paid services now, e.g. capsolver

**Comment by sheldygg** [comment]
I found a way to generate x-kpsdk-cd, but I still need x-kpsdk-ct, I still have no idea how to get it. at the moment I get it using selenium

**Comment by mrsnifo** [comment]
Any updates 😂😂?

**Comment by Kappador** [comment]
Nah
